name: matrix-clicker

services:
  server:
    build:
      context: ./server
    image: harbor.sch.bme.hu/org-kir-dev/matrix-clicker-server:latest
    container_name: matrix-clicker-server
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: unless-stopped

  client:
    build:
      context: ./client
    image: harbor.sch.bme.hu/org-kir-dev/matrix-clicker-client:latest
    container_name: matrix-clicker-client
    ports:
      - "3000:80"
    environment:
      VITE_API_BASE_URL: http://localhost:8080
      VITE_WS_BASE_URL: ws://localhost:8080
    depends_on:
      - server
    restart: unless-stopped
